import mongoose, { Schema, model, models } from "mongoose";

const codeSchema = new mongoose.Schema({
  code: { type: Number, required: true },
  name: { type: String, required: true },
  stock: { type: Number, default: 0 },
  company: { type: String, default: "" },
  Elzaafran: { type: Number, default: 0 },
  Hokok: { type: Number, default: 0 },
  Khulfaa: { type: Number, default: 0 },
  Kolytadab: { type: Number, default: 0 },
  madenty: { type: Number, default: 0 },
  portSaid: { type: Number, default: 0 },
  porsaid_st: { type: Number, default: 0 },
  semad: { type: Number, default: 0 },
  zagazig: { type: Number, default: 0 },
  arkhan: { type: Number, default: 0 },
  awel_khulfa: { type: Number, default: 0 },
  awel_march: { type: Number, default: 0 },
  ismailia: { type: Number, default: 0 },
  gala2: { type: Number, default: 0 },
  gomhorya: { type: Number, default: 0 },
  golf: { type: Number, default: 0 },
  drasat: { type: Number, default: 0 },
  rehab: { type: Number, default: 0 },
  swees: { type: Number, default: 0 },
  mohafza: { type: Number, default: 0 },
  m_aam: { type: Number, default: 0 },
  manzala: { type: Number, default: 0 },
  new_domyat: { type: Number, default: 0 },
  estad: { type: Number, default: 0 },
  gamaa: { type: Number, default: 0 },
  geesh: { type: Number, default: 0 },
  seka: { type: Number, default: 0 },
  bank_masr: { type: Number, default: 0 },
  porsaid_st: { type: Number, default: 0 },
  domyat: { type: Number, default: 0 },
  sheraton: { type: Number, default: 0 },
  kanat_swees: { type: Number, default: 0 },
  m_nasr: { type: Number, default: 0 },
});

const CodeModel = models.Code || model("Code", codeSchema);

export default CodeModel;
